<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">

  <xacro:arg name="wheel_diameter" default="0.254"/>

  <xacro:property name="wheel_radius" value="${$(arg wheel_diameter)/2}"/>
  <xacro:property name="wheel_width" value="0.05"/>

  <xacro:property name="wheelbase_length" value="0.6096"/>
  <xacro:property name="front_wheelbase_width" value="0.4572"/>
  <xacro:property name="rear_wheelbase_width" value="0.4572"/>
  <xacro:property name="wheel_mass" value="1"/>
  <xacro:property name="total_mass" value = "5.0"/>
  <xacro:property name="shock_travel" value = "0.035"/>  
  <xacro:property name="shock_height" value = "0.2"/>
  <xacro:property name="chassis_height" value = "0.0254"/>
  <xacro:property name="chassis_elevation" value = "0.3"/>
  <xacro:property name="chassis_mass" value = "${total_mass-4*wheel_mass}"/>
  <xacro:property name="chassis_l" value = "0.9144"/>
  <xacro:property name="chassis_w" value = "0.6096"/>
  <xacro:property name="chassis_t" value = "0.0254"/>
  <xacro:property name="steering_limit" value = "1"/>


  <xacro:macro name="cylinder_inertia" params="m r h">
        <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
                    iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
                    izz="${m*r*r/2}" /> 
  </xacro:macro>

  <xacro:macro name="box_inertia" params="m x y z">
          <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
                    iyy="${m*(x*x+z*z)/12}" iyz = "0"
                    izz="${m*(x*x+z*z)/12}" /> 
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
          <inertia  ixx="${2*m*r*r/5}" ixy = "0" ixz = "0"
                    iyy="${2*m*r*r/5}" iyz = "0"
                    izz="${2*m*r*r/5}" /> 
  </xacro:macro>

  <xacro:macro name="cylinder_inertial" params="m r h">
    <inertial>
      <mass value="${m}"/>
      <xacro:cylinder_inertia m="${m}" r="${r}" h="${h}"/>
    </inertial>
  </xacro:macro>

  <link name="base_footprint"/>

  <link name="base_link"/>
<!--
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.2" radius="0.01"/>
      </geometry>
      <material name="silver">
        <color rgba="0.75 0.75 0.75 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.2" radius="0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.015" iyy="0.0375" izz="0.0375"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>
-->
  <link name="chassis_link">
    <visual>
      <geometry>
        <box size="${chassis_l} ${chassis_w} ${chassis_t}"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_l} ${chassis_w} ${chassis_t}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${chassis_mass}"/>
      <xacro:box_inertia m="${chassis_mass}" x="${chassis_l}" y="${chassis_w}" z="${chassis_t}"/>
    </inertial>
  </link>

  <link name="back_left_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <xacro:cylinder_inertial m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
  </link>



  <link name="back_right_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertial m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
  </link>

  <link name="front_left_wheel_steer">
    <visual>
      <geometry>
        <cylinder length="0.01" radius="0.01"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.01" radius="0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="5.1458e-5" iyy="5.1458e-5" izz="6.125e-5"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>  
    <link name="front_left_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertial m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
  </link>

  <link name="front_right_wheel_steer">
    <visual>
      <geometry>
        <cylinder length="0.01" radius="0.01"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.01" radius="0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="5.1458e-5" iyy="5.1458e-5" izz="6.125e-5"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>  

  <link name="front_right_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertial m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
  </link>

  <link name="back_left_wheel_shock">
      <visual>
      <origin xyz="0 0 ${shock_height}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.05" radius="0.01"/>
      </geometry>
      <material name="silver">
        <color rgba="0.75 0.75 0.75 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${shock_height}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.05" radius="0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.015" iyy="0.0375" izz="0.0375"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <link name="back_right_wheel_shock">
    <visual>
    <origin xyz="0 0 ${shock_height}" rpy="0 0 0"/>
    <geometry>
      <cylinder length="0.05" radius="0.01"/>
    </geometry>
    <material name="silver">
      <color rgba="0.75 0.75 0.75 1"/>
    </material>
  </visual>
  <collision>
    <origin xyz="0 0 ${shock_height}" rpy="0 0 0"/>
    <geometry>
      <cylinder length="0.05" radius="0.01"/>
    </geometry>
  </collision>
  <inertial>
    <mass value="0.01"/>
    <inertia ixx="0.015" iyy="0.0375" izz="0.0375"
              ixy="0" ixz="0" iyz="0"/>
  </inertial>
</link>

  <link name="front_left_wheel_shock">
      <visual>
      <origin xyz="0 0 ${shock_height}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.05" radius="0.01"/>
      </geometry>
      <material name="silver">
        <color rgba="0.75 0.75 0.75 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${shock_height}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.05" radius="0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.015" iyy="0.0375" izz="0.0375"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <link name="front_right_wheel_shock">
      <visual>
      <origin xyz="0 0 ${shock_height}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.05" radius="0.01"/>
      </geometry>
      <material name="silver">
        <color rgba="0.75 0.75 0.75 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${shock_height}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.05" radius="0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.015" iyy="0.0375" izz="0.0375"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>


  <joint name="base_link_joint" type="fixed">
     <parent link="base_footprint"/>
     <child link="base_link"/>
     <origin rpy="0 0 0" xyz="0 0 0"/>
   </joint>



  <joint name="back_left_shock_joint" type="prismatic">
    <limit lower="0" upper="${shock_travel}" effort="100" velocity="100"/>
    <axis xyz="0 0 1"/>
    <parent link="base_link"/>
    <child link="back_left_wheel_shock"/>
    <origin rpy="0 0 0" xyz="0 ${rear_wheelbase_width/2}  ${wheel_radius}"/>
  </joint>

  <joint name="back_left_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="back_left_wheel_shock"/>
    <child link="back_left_wheel"/>
    <origin rpy="${-pi/2} 0 0" xyz="0 0 0"/>
    <limit effort="10000" velocity="1" />
  </joint>




  <joint name="back_right_shock_joint" type="prismatic">
    <limit lower="0" upper="${shock_travel}" effort="100" velocity="100"/>
    <axis xyz="0 0 1"/>
    <parent link="base_link"/>
    <child link="back_right_wheel_shock"/>
    <origin rpy="0 0 0" xyz="0 ${-rear_wheelbase_width/2} ${wheel_radius}"/>
  </joint>

  <joint name="back_right_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="back_right_wheel_shock"/>
    <child link="back_right_wheel"/>
    <origin rpy="${-pi/2} 0 0" xyz="0 0 0"/>
    <limit effort="10000" velocity="500" />
  </joint>



  <joint name="front_right_shock_joint" type="prismatic">
    <limit lower="0" upper="${shock_travel}" effort="100" velocity="100"/>
    <axis xyz="0 0 1"/>
    <parent link="base_link"/>
    <child link="front_right_wheel_shock"/>
    <origin rpy="0 0 0" xyz="${wheelbase_length} ${-front_wheelbase_width/2} ${wheel_radius}"/>
  </joint>


  <joint name="front_left_shock_joint" type="prismatic">
    <limit lower="0" upper="${shock_travel}" effort="100" velocity="100"/>
    <axis xyz="0 0 1"/>
    <parent link="base_link"/>
    <child link="front_left_wheel_shock"/>
    <origin rpy="0 0 0" xyz="${wheelbase_length} ${front_wheelbase_width/2} ${wheel_radius}"/>
  </joint>


  <joint name="front_left_wheel_steer_joint" type="revolute">
    <limit lower="${-steering_limit}" upper="${steering_limit}" effort="1" velocity="1"/>
    <axis xyz="0 0 1"/>
    <parent link="front_left_wheel_shock"/>
    <child link="front_left_wheel_steer"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </joint>

  <joint name="front_left_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="front_left_wheel_steer"/>
    <child link="front_left_wheel"/>
    <origin rpy="${-pi/2} 0 0" xyz="0 0 0"/>
  </joint>

  <joint name="front_right_wheel_steer_joint" type="revolute">
    <limit lower="${-steering_limit}" upper="${steering_limit}" effort="1" velocity="1"/>
    <axis xyz="0 0 1"/>
    <parent link="front_right_wheel_shock"/>
    <child link="front_right_wheel_steer"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </joint>

  <joint name="front_right_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="front_right_wheel_steer"/>
    <child link="front_right_wheel"/>
    <origin rpy="${-pi/2} 0 0" xyz="0 0 0"/>
  </joint>

  <joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_link"/>
    <origin rpy="0 0 0" xyz="${wheelbase_length/2} 0 ${chassis_height/2 + chassis_elevation}"/>
  </joint>


  
</robot>

